<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://localhost:8081/dcms/webservice/QueryRecord" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://localhost:8081/dcms/webservice/QueryRecord" xmlns:intf="http://localhost:8081/dcms/webservice/QueryRecord" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->

   <wsdl:message name="queryRecordAddrRequest">

      <wsdl:part name="EnterpriseID" type="xsd:string"/>

      <wsdl:part name="USER" type="xsd:string"/>

      <wsdl:part name="PASSWORD" type="xsd:string"/>

      <wsdl:part name="SessionID" type="xsd:string"/>

   </wsdl:message>

   <wsdl:message name="queryRecordAddrResponse">

      <wsdl:part name="return" type="xsd:string"/>

   </wsdl:message>

   <wsdl:portType name="QueryRecord">

      <wsdl:operation name="queryRecordAddr" parameterOrder="EnterpriseID USER PASSWORD SessionID">

         <wsdl:input message="impl:queryRecordAddrRequest" name="queryRecordAddrRequest"/>

         <wsdl:output message="impl:queryRecordAddrResponse" name="queryRecordAddrResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="QueryRecordSoapBinding" type="impl:QueryRecord">

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="queryRecordAddr">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="queryRecordAddrRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://localhost:8081/dcms/webservice/QueryRecord" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="queryRecordAddrResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://localhost:8081/dcms/webservice/QueryRecord" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="QueryRecordService">

      <wsdl:port binding="impl:QueryRecordSoapBinding" name="QueryRecord">

         <wsdlsoap:address location="http://ccod4.5d:8080/dcmsWebservice/webservice/QueryRecord"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
